name: All

on:
    push: 
        branches: '*'
    pull_request: 
        branches: '*'

        
jobs:
    tests:
        name: Tests Unitaires
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0