name: All

on:
    push: 
        branches: '*'
    pull_request: 
        branches: '*'

        
jobs:
    tests:
        name: Tests Unitaires
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Installation de Node.js
              uses: actions/setup-node@v3

            - name: Installation de Node.js
              run: npm install
              
            - name: Test unitaire
              run: npm run tests-unitaires
            
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
          